exports.EventType = {
    ROLE_RECEVIVE_ALL: "ROLE_RECEVIVE_ALL",
    ROLE_ADD: "ROLE_ADD",
    ROlE_UPDATE: "ROLE_UPDATE",
    USER_GET_LIST: "USER_GET_LIST",
    UI_OPEN_ROLE_FORM: "UI_OPEN_ROLE_FORM"
};
