exports.EventType = {
    ROLES_RECEVIVE_ALL: "ROLES_RECEVIVE_ALL",
    ROLES_RECEVIVE_CREATE: "ROLES_RECEVIVE_CREATE",
    ROLES_RESET_ALL: "ROLES_RESET_ALL",
    UI_OPEN_ROLE_FORM: "UI_OPEN_ROLE_FORM"
};
